# docker-compose.yml

version: '3'
services:
  posthog:
    image: posthog/posthog:latest
    environment:
      - POSTHOG_SECRET=${POSTHOG_SECRET}
      - SENTRY_DSN=${SENTRY_DSN}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
